export const adjectives: string[] = [
  "Apex",
  "Atomic",
  "Automated",
  "Autonomous",
  "Brutalist",
  "Cast-Iron",
  "Centralized",
  "Cryogenic",
  "Cybernetic",
  "Dominion",
  "Failsafe",
  "Fiscal",
  "Fortified",
  "Galvanized",
  "Geothermal",
  "Heavy-Duty",
  "Hydraulic",
  "Integrated",
  "Isotopic",
  "Kinetic",
  "Magnetic",
  "Mandated",
  "Modular",
  "Molecular",
  "Monolithic",
  "Nuclear",
  "Optimal",
  "Optimized",
  "Orbital",
  "Perpetual",
  "Photon",
  "Plasma",
  "Pneumatic",
  "Prefabricated",
  "Prime",
  "Priority",
  "Productive",
  "Quantum",
  "Radiant",
  "Reinforced",
  "Sonic",
  "Sovereign",
  "Standardized",
  "Subterranean",
  "Synthetic",
  "Systematic",
  "Tectonic",
  "Thermal",
  "Titanic",
  "Tubular",
  "Unbroken",
  "Voltaic",
];

export const nouns: string[] = [
  "Anchor",
  "Array",
  "Assembler",
  "Assembly",
  "Bay",
  "Block",
  "Citadel",
  "Complex",
  "Compound",
  "Conduit",
  "Core",
  "Crusher",
  "Depot",
  "District",
  "Exchange",
  "Extractor",
  "Forge",
  "Foundry",
  "Generator",
  "Grid",
  "Hangar",
  "Hive",
  "Hub",
  "Junction",
  "Kiln",
  "Logistics",
  "Loom",
  "Manufacturer",
  "Matrix",
  "Mill",
  "Monolith",
  "Network",
  "Nexus",
  "Outpost",
  "Pipeline",
  "Plant",
  "Press",
  "Reactor",
  "Refinery",
  "Reservoir",
  "Sector",
  "Silicosis",
  "Silo",
  "Smelter",
  "Spire",
  "Station",
  "Synthesizer",
  "Terminal",
  "Vault",
  "Venture",
  "Workshop",
];

function pick<T>(arr: T[]): T {
  return arr[Math.floor(Math.random() * arr.length)];
}

export function generateFactoryName(): string {
  const adjective = pick(adjectives);
  const noun = pick(nouns);
  return `${adjective} ${noun}`;
}
